# Generated by Django 2.2 on 2020-02-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='EAD7F3D8-EB32-47A0-8296-E96A13320D4D.jpeg', upload_to='profile_pics'),
        ),
    ]
