# Generated by Django 2.2 on 2020-03-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksearch', '0002_mystock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystock',
            name='stockname',
            field=models.TextField(null=True, unique=True),
        ),
    ]
