# Generated by Django 2.2 on 2020-03-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksearch', '0003_auto_20200306_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystock',
            name='stockname',
            field=models.TextField(default=None, unique=True),
        ),
    ]
