# Generated by Django 2.2 on 2020-03-10 12:50

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocksearch', '0008_mystock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresults',
            name='field',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
