# Generated by Django 2.2 on 2020-03-11 08:32

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocksearch', '0009_searchresults_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresults',
            name='field1',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
