# Generated by Django 2.2 on 2020-03-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksearch', '0012_news_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresults',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
